### PR TITLE
Add threshold parameter for filtering below a certain allergen level

### PR DESCRIPTION
**Pull request by geeak**
Added an optional 'threshold' parameter that will filter the allergens depending on the level for the current and coming days. E.g. if threshold is set to '3' then the card will will show any of the allergens configured in the card if the state is 3 or higher in the current or coming two days.

### CODE REVIEW

**Comment by isabellaalstrom** [comment]
I actually wrote this a couple of days ago and have been testing locally, but I included some of your changes in the code i committed today. So I am closing this, but some of your ideas are included! :)

**Comment by geeak** [comment]
Ok, great. My approach was rather ungraceful in handling missing states, and yours is not as braindead as my solution.

**Comment by Ranur** [comment]
Threshold doesn't work for me. Have updated to card 0.2.0 and set threshold to 1. Still I get all icons in the card - even the one with "inga halter"

**Comment by isabellaalstrom** [comment]
Have a look at these links:
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#updating-a-plugin
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#common-problems

**Comment by Ranur** [comment]
Sooo noob! Cache issue! Thanks!

**Pull request closed without merging**
